package com.example.englishwords2

object KelimeSeedData {

    fun getKelimeler(): List<KelimeEntity> = listOf(
        KelimeEntity(ingilizce = "pencil", turkce = "kalem"),
        KelimeEntity(ingilizce = "book", turkce = "kitap"),
        KelimeEntity(ingilizce = "table", turkce = "masa"),
        KelimeEntity(ingilizce = "chair", turkce = "sandalye"),
        KelimeEntity(ingilizce = "phone", turkce = "telefon"),
        KelimeEntity(ingilizce = "house", turkce = "ev"),
        KelimeEntity(ingilizce = "door", turkce = "kapı"),
        KelimeEntity(ingilizce = "window", turkce = "pencere"),
        KelimeEntity(ingilizce = "water", turkce = "su"),
        KelimeEntity(ingilizce = "food", turkce = "yemek"),
        KelimeEntity(ingilizce = "school", turkce = "okul"),
        KelimeEntity(ingilizce = "bag", turkce = "çanta"),
        KelimeEntity(ingilizce = "road", turkce = "yol"),
        KelimeEntity(ingilizce = "tree", turkce = "ağaç"),
        KelimeEntity(ingilizce = "sun", turkce = "güneş"),
        KelimeEntity(ingilizce = "moon", turkce = "ay"),
        KelimeEntity(ingilizce = "pen", turkce = "tükenmez kalem"),
        KelimeEntity(ingilizce = "clock", turkce = "saat"),
        KelimeEntity(ingilizce = "bread", turkce = "ekmek"),
        KelimeEntity("accountant", "muhasebeci"),
    KelimeEntity("afraid", "korkmuş"),
    KelimeEntity("age", "yaş"),
    KelimeEntity("airplane", "uçak"),
    KelimeEntity("alone", "yalnız"),
    KelimeEntity("angry", "kızgın-sinirli"),
    KelimeEntity("animal", "hayvan"),
    KelimeEntity("answer", "cevap vermek"),
    KelimeEntity("architect", "mimar"),
    KelimeEntity("arrive", "varmak"),
    KelimeEntity("aunt", "hala-teyze"),
    KelimeEntity("bag", "çanta"),
    KelimeEntity("ball", "top"),
    KelimeEntity("bath", "banyo"),
    KelimeEntity("beautiful", "güzel"),
    KelimeEntity("bill", "hesap-fatura"),
    KelimeEntity("body", "vücut"),
    KelimeEntity("boil", "kaynamak"),
    KelimeEntity("bookstore", "kitapçı"),
    KelimeEntity("boring", "sıkıcı"),
    KelimeEntity("borrow", "ödünç almak"),
    KelimeEntity("boss", "patron"),
    KelimeEntity("bottle", "şişe"),
    KelimeEntity("box", "kutu"),
    KelimeEntity("brave", "cesur"),
    KelimeEntity("bread", "ekmek"),
    KelimeEntity("break", "kırmak"),
    KelimeEntity("bridge", "köprü"),
    KelimeEntity("brush", "fırça"),
    KelimeEntity("build", "inşa etmek"),
    KelimeEntity("butter", "tere yağı"),
    KelimeEntity("calculator", "hesap makinası"),
    KelimeEntity("calendar", "takvim"),
    KelimeEntity("call", "aramak"),
    KelimeEntity("capital", "başkent"),
    KelimeEntity("carpenter", "marangoz"),
    KelimeEntity("carpet", "halı"),
    KelimeEntity("carry", "taşımak"),
    KelimeEntity("cartoon", "çizgi film"),
    KelimeEntity("chair", "sandalye"),
    KelimeEntity("cheap", "ucuz"),
    KelimeEntity("cheese", "peynir"),
    KelimeEntity("cherry", "kiraz"),
    KelimeEntity("chicken", "tavuk"),
    KelimeEntity("church", "kilise"),
    KelimeEntity("clean", "temizlemek"),
    KelimeEntity("clear", "açık, net"),
    KelimeEntity("clever", "akıllı"),
    KelimeEntity("clock", "saat"),
    KelimeEntity("cloud", "bulut"),

    // ===== PAKET 2 =====
    KelimeEntity("plane", "uçak"),
    KelimeEntity("pocket", "cep"),
    KelimeEntity("polite", "kibar"),
    KelimeEntity("pool", "havuz"),
    KelimeEntity("poor", "fakir"),
    KelimeEntity("possible", "mümkün"),
    KelimeEntity("push", "ittirmek"),
    KelimeEntity("quick", "hızlı"),
    KelimeEntity("quiet", "sessiz"),
    KelimeEntity("railway", "tren yolu"),
    KelimeEntity("ready", "hazır"),
    KelimeEntity("refrigerator", "buzdolabı"),
    KelimeEntity("remember", "hatırlamak"),
    KelimeEntity("rent", "kiralamak"),
    KelimeEntity("repair", "tamir etmek"),
    KelimeEntity("repeat", "tekrar etmek"),
    KelimeEntity("restroom", "tuvalet"),
    KelimeEntity("return", "geri dönmek"),
    KelimeEntity("rice", "pirinç"),
    KelimeEntity("rich", "zengin"),
    KelimeEntity("ride", "binmek"),
    KelimeEntity("right", "doğru"),
    KelimeEntity("ring", "yüzük-telefonun çalması"),
    KelimeEntity("rise", "güneş(doğmak)"),
    KelimeEntity("river", "ırmak"),
    KelimeEntity("road", "yol"),
    KelimeEntity("roof", "çatı"),
    KelimeEntity("room", "oda"),
    KelimeEntity("rose", "gül"),
    KelimeEntity("salt", "tuz"),
    KelimeEntity("same", "aynı / benzer "),
    KelimeEntity("security", "güvenlik"),
    KelimeEntity("sell", "satmak"),
    KelimeEntity("serious", "ciddi"),
    KelimeEntity("shelf", "raf"),
    KelimeEntity("ship", "gemi"),
    KelimeEntity("shirt", "gömlek"),
    KelimeEntity("shoe", "ayakkabı"),
    KelimeEntity("show", "göstermek"),
    KelimeEntity("sick", "hasta"),
    KelimeEntity("sing", "şarkı söylemek"),
    KelimeEntity("single", "bekar"),
    KelimeEntity("skirt", "etek"),
    KelimeEntity("sky", "gökyüzü"),
    KelimeEntity("smile", "gülümsemek"),
    KelimeEntity("snow", "kar"),
    KelimeEntity("socks", "çorap"),
    KelimeEntity("son", "erkek çocuk"),
    KelimeEntity("song", "şarkı"),
    KelimeEntity("soup", "çorba"),

    // ===== PAKET 3 =====
    KelimeEntity("serve", "servis yapmak"),
    KelimeEntity("sharp", "keskin,sivri"),
    KelimeEntity("shine", "parlamak"),
    KelimeEntity("shoulder", "omuz"),
    KelimeEntity("shout", "bağırmak"),
    KelimeEntity("sign", "imza atmak"),
    KelimeEntity("silent", "sessiz"),
    KelimeEntity("simple", "basit"),
    KelimeEntity("situation", "durum"),
    KelimeEntity("ski", "kayak"),
    KelimeEntity("snake", "yılan"),
    KelimeEntity("soap", "sabun"),
    KelimeEntity("society", "sosyete"),
    KelimeEntity("soft", "yumuşak"),
    KelimeEntity("spider", "örümcek"),
    KelimeEntity("stand", "ayakta durmak"),
    KelimeEntity("stone", "taş"),
    KelimeEntity("storm", "fırtına"),
    KelimeEntity("subway", "metro"),
    KelimeEntity("sure", "emin olmak"),
    KelimeEntity("surprised", "şaşırmış"),
    KelimeEntity("tailor", "terzi"),
    KelimeEntity("taste", "tatmak"),
    KelimeEntity("team", "takım"),
    KelimeEntity("temperature", "derece,ısı"),
    KelimeEntity("tent", "çadır"),
    KelimeEntity("terrible", "berbat"),
    KelimeEntity("throw", "atmak,fırlatmak"),
    KelimeEntity("tiger", "kaplan"),
    KelimeEntity("tissue", "kağıt mendil"),
    KelimeEntity("tongue", "dil"),
    KelimeEntity("touch", "dokumak"),
    KelimeEntity("transport", "nakil, taşıma"),
    KelimeEntity("trouble", "dert"),
    KelimeEntity("try", "denemek"),
    KelimeEntity("usual", "olağan"),
    KelimeEntity("vacation", "tatil"),
    KelimeEntity("vacuum cleaner", "elektrik süpürgesi"),
    KelimeEntity("valuable", "değerli"),
    KelimeEntity("vegetable", "sebze"),
    KelimeEntity("view", "manzara, görünüm"),
    KelimeEntity("voice", "ses"),
    KelimeEntity("war", "savaş"),
    KelimeEntity("warm", "ılık"),
    KelimeEntity("warning", "uyarı"),
    KelimeEntity("weather", "hava"),
    KelimeEntity("wet", "ıslak"),
    KelimeEntity("win", "kazanmak"),
    KelimeEntity("wine", "şarap"),
    KelimeEntity("worry", "endişe"),

    // ===== PAKET 4 =====
    KelimeEntity("coin", "madeni para"),
    KelimeEntity("comb", "tarak"),
    KelimeEntity("common", "yaygın"),
    KelimeEntity("communicate", "iletişim kurmak"),
    KelimeEntity("compare", "kıyaslamak"),
    KelimeEntity("complain", "şikayet etmek"),
    KelimeEntity("connected flight", "aktarmalı uçuş"),
    KelimeEntity("consist", "oluşmak"),
    KelimeEntity("contain", "içermek"),
    KelimeEntity("convince", "ikna etmek"),
    KelimeEntity("count", "saymak"),
    KelimeEntity("crime", "suç"),
    KelimeEntity("criticize", "eleştiri yapmak"),
    KelimeEntity("curtain", "perde"),
    KelimeEntity("death", "ölüm"),
    KelimeEntity("decrease", "azalmak"),
    KelimeEntity("defend", "savunmak"),
    KelimeEntity("departure gate", "çıkış kapısı"),
    KelimeEntity("destination", "varış"),
    KelimeEntity("destroy", "yok etmek"),
    KelimeEntity("detail", "detay"),
    KelimeEntity("development", "gelişim"),
    KelimeEntity("disagree", "aynı fikirde olmamak"),
    KelimeEntity("discount", "indirim"),
    KelimeEntity("disease", "hastalık"),
    KelimeEntity("dive", "dalmak"),
    KelimeEntity("divide", "bölmek"),
    KelimeEntity("domestic flight", "iç hat uçuşu"),
    KelimeEntity("drop", "düşürmek"),
    KelimeEntity("drug", "ilaç,uyuşturucu"),
    KelimeEntity("dry", "kuru"),
    KelimeEntity("duty", "görev"),
    KelimeEntity("earthquake", "deprem"),
    KelimeEntity("education", "eğitim"),
    KelimeEntity("effort", "çaba"),
    KelimeEntity("elegant", "zarif"),
    KelimeEntity("employer", "işveren"),
    KelimeEntity("engine", "motor"),
    KelimeEntity("environment", "çevre"),
    KelimeEntity("event", "etkinlik,olay"),
    KelimeEntity("excuse", "mazeret"),
    KelimeEntity("expect", "ummak"),
    KelimeEntity("explosion", "patlama"),
    KelimeEntity("express", "ifade etmek"),
    KelimeEntity("fact", "gerçek"),
    KelimeEntity("fair", "adil"),
    KelimeEntity("fear", "korkmak"),
    KelimeEntity("feed", "beslemek"),
    KelimeEntity("field", "tarla"),
    KelimeEntity("fist", "yumruk"),

    // ===== PAKET 5 =====
    KelimeEntity("client", "müşteri"),
    KelimeEntity("coal", "kömür"),
    KelimeEntity("comment", "yorum"),
    KelimeEntity("commerce", "ticaret"),
    KelimeEntity("commercial", "reklam"),
    KelimeEntity("community", "cemiyet"),
    KelimeEntity("competition", "rekabet"),
    KelimeEntity("complaint", "şikayet"),
    KelimeEntity("concentrate", "konsantre olmak"),
    KelimeEntity("condition", "durum,koşul"),
    KelimeEntity("confess", "itirafta bulunmak"),
    KelimeEntity("congratulate", "tebrik etmek"),
    KelimeEntity("congress", "kongre,meclis"),
    KelimeEntity("consider", "göz önünde bulundurmak"),
    KelimeEntity("construction", "inşaat"),
    KelimeEntity("consult", "danışmak"),
    KelimeEntity("contest", "yarışma"),
    KelimeEntity("contribute", "katkıda bulunmak"),
    KelimeEntity("convert", "dönüştürmek"),
    KelimeEntity("court", "mahkeme"),
    KelimeEntity("crossword", "bulmaca"),
    KelimeEntity("cruel", "zalim"),
    KelimeEntity("customs", "gümrük,töre"),
    KelimeEntity("dashboard", "gösterge paneli"),
    KelimeEntity("deadline", "son tarih"),
    KelimeEntity("deceive", "aldatmak"),
    KelimeEntity("declare", "ilan etmek"),
    KelimeEntity("define", "tanımlamak"),
    KelimeEntity("deflation", "deflasyon,çökme"),
    KelimeEntity("depend", "dayanmak / bağlı olmak"),
    KelimeEntity("desire", "arzu etmek"),
    KelimeEntity("devaluation", "değer düşürme"),
    KelimeEntity("diagnose", "teşhis"),
    KelimeEntity("disappear", "ortadan kaybolmak"),
    KelimeEntity("disappoint", "hayal kırıklığına uğramak"),
    KelimeEntity("distance", "mesafe"),
    KelimeEntity("distribution", "dağıtım"),
    KelimeEntity("dreadful", "korkunç"),
    KelimeEntity("eager", "hevesli"),
    KelimeEntity("election", "seçim"),
    KelimeEntity("embassy", "büyükelçilik"),
    KelimeEntity("encourage", "teşvik etmek"),
    KelimeEntity("enemy", "düşman"),
    KelimeEntity("enterprise", "işletme,şirket"),
    KelimeEntity("entrepreneur", "girişimci,işletmeci"),
    KelimeEntity("envy", "imrenmek"),
    KelimeEntity("essay", "makale"),
    KelimeEntity("establish", "kurmak"),
    KelimeEntity("estimate", "tahmin etmek"),
    KelimeEntity("evaluate", "değerlendirmek"),

        //====VERBS KELİMELERİ==\\

    KelimeEntity("eat", "yemek", "VERBS"),
    KelimeEntity("drink", "içmek", "VERBS"),
    KelimeEntity("run", "koşmak", "VERBS"),
    KelimeEntity("walk", "yürümek", "VERBS"),
    KelimeEntity("sleep", "uyumak", "VERBS"),
    KelimeEntity("wake", "uyanmak", "VERBS"),
    KelimeEntity("go", "gitmek", "VERBS"),
    KelimeEntity("come", "gelmek", "VERBS"),
    KelimeEntity("see", "görmek", "VERBS"),
    KelimeEntity("look", "bakmak", "VERBS"),
    KelimeEntity("hear", "duymak", "VERBS"),
    KelimeEntity("listen", "dinlemek", "VERBS"),
    KelimeEntity("speak", "konuşmak", "VERBS"),
    KelimeEntity("say", "söylemek", "VERBS"),
    KelimeEntity("tell", "anlatmak", "VERBS"),
    KelimeEntity("ask", "sormak", "VERBS"),
    KelimeEntity("answer", "cevap vermek", "VERBS"),
    KelimeEntity("think", "düşünmek", "VERBS"),
    KelimeEntity("know", "bilmek", "VERBS"),
    KelimeEntity("learn", "öğrenmek", "VERBS"),
    KelimeEntity("teach", "öğretmek", "VERBS"),
    KelimeEntity("study", "ders çalışmak", "VERBS"),
    KelimeEntity("work", "çalışmak", "VERBS"),
    KelimeEntity("play", "oynamak", "VERBS"),
    KelimeEntity("win", "kazanmak", "VERBS"),
    KelimeEntity("lose", "kaybetmek", "VERBS"),
    KelimeEntity("open", "açmak", "VERBS"),
    KelimeEntity("close", "kapatmak", "VERBS"),
    KelimeEntity("start", "başlamak", "VERBS"),
    KelimeEntity("finish", "bitirmek", "VERBS"),
    KelimeEntity("stop", "durmak", "VERBS"),
    KelimeEntity("wait", "beklemek", "VERBS"),
    KelimeEntity("help", "yardım etmek", "VERBS"),
    KelimeEntity("try", "denemek", "VERBS"),
    KelimeEntity("use", "kullanmak", "VERBS"),
    KelimeEntity("make", "yapmak", "VERBS"),
    KelimeEntity("build", "inşa etmek", "VERBS"),
    KelimeEntity("break", "kırmak", "VERBS"),
    KelimeEntity("fix", "tamir etmek", "VERBS"),
    KelimeEntity("buy", "satın almak", "VERBS"),
    KelimeEntity("sell", "satmak", "VERBS"),
    KelimeEntity("pay", "ödemek", "VERBS"),
    KelimeEntity("save", "biriktirmek", "VERBS"),
    KelimeEntity("spend", "harcamak", "VERBS"),
    KelimeEntity("travel", "seyahat etmek", "VERBS"),
    KelimeEntity("drive", "araba sürmek", "VERBS"),
    KelimeEntity("ride", "binmek", "VERBS"),
    KelimeEntity("fly", "uçmak", "VERBS"),
    KelimeEntity("arrive", "varmak", "VERBS"),
    KelimeEntity("leave", "ayrılmak", "VERBS"),
    KelimeEntity("enter", "girmek", "VERBS"),
    KelimeEntity("exit", "çıkmak", "VERBS"),
    KelimeEntity("turn", "dönmek", "VERBS"),
    KelimeEntity("return", "geri dönmek", "VERBS"),
    KelimeEntity("bring", "getirmek", "VERBS"),
    KelimeEntity("take", "almak", "VERBS"),
    KelimeEntity("give", "vermek", "VERBS"),
    KelimeEntity("hold", "tutmak", "VERBS"),
    KelimeEntity("drop", "düşürmek", "VERBS"),
    KelimeEntity("carry", "taşımak", "VERBS"),
    KelimeEntity("push", "itmek", "VERBS"),
    KelimeEntity("pull", "çekmek", "VERBS"),
    KelimeEntity("cut", "kesmek", "VERBS"),
    KelimeEntity("cook", "pişirmek", "VERBS"),
    KelimeEntity("boil", "kaynatmak", "VERBS"),
    KelimeEntity("bake", "fırında pişirmek", "VERBS"),
    KelimeEntity("clean", "temizlemek", "VERBS"),
    KelimeEntity("wash", "yıkamak", "VERBS"),
    KelimeEntity("dry", "kurutmak", "VERBS"),
    KelimeEntity("wear", "giymek", "VERBS"),
    KelimeEntity("change", "değiştirmek", "VERBS"),
    KelimeEntity("choose", "seçmek", "VERBS"),
    KelimeEntity("decide", "karar vermek", "VERBS"),
    KelimeEntity("agree", "kabul etmek", "VERBS"),
    KelimeEntity("disagree", "aynı fikirde olmamak", "VERBS"),
    KelimeEntity("believe", "inanmak", "VERBS"),
    KelimeEntity("hope", "umut etmek", "VERBS"),
    KelimeEntity("want", "istemek", "VERBS"),
    KelimeEntity("need", "ihtiyaç duymak", "VERBS"),
    KelimeEntity("like", "sevmek", "VERBS"),
    KelimeEntity("love", "aşık olmak", "VERBS"),
    KelimeEntity("hate", "nefret etmek", "VERBS"),
    KelimeEntity("feel", "hissetmek", "VERBS"),
    KelimeEntity("smile", "gülümsemek", "VERBS"),
    KelimeEntity("laugh", "gülmek", "VERBS"),
    KelimeEntity("cry", "ağlamak", "VERBS"),
    KelimeEntity("shout", "bağırmak", "VERBS"),
    KelimeEntity("call", "aramak", "VERBS"),
    KelimeEntity("answer", "cevaplamak", "VERBS"),
    KelimeEntity("text", "mesaj atmak", "VERBS"),
    KelimeEntity("meet", "buluşmak", "VERBS"),
    KelimeEntity("visit", "ziyaret etmek", "VERBS"),
    KelimeEntity("invite", "davet etmek", "VERBS"),
    KelimeEntity("welcome", "karşılamak", "VERBS"),
    KelimeEntity("protect", "korumak", "VERBS"),
    KelimeEntity("attack", "saldırmak", "VERBS"),
    KelimeEntity("defend", "savunmak", "VERBS"),
    KelimeEntity("fight", "dövüşmek", "VERBS"),
    KelimeEntity("hide", "saklanmak", "VERBS"),
    KelimeEntity("seek", "aramak", "VERBS"),
    KelimeEntity("find", "bulmak", "VERBS"),
    KelimeEntity("lose", "kaybetmek", "VERBS"),
    KelimeEntity("improve", "geliştirmek", "VERBS"),
    KelimeEntity("grow", "büyümek", "VERBS"),
    KelimeEntity("increase", "artmak", "VERBS"),
    KelimeEntity("decrease", "azalmak", "VERBS"),
    KelimeEntity("create", "oluşturmak", "VERBS"),
    KelimeEntity("destroy", "yok etmek", "VERBS"),
    KelimeEntity("design", "tasarlamak", "VERBS"),
    KelimeEntity("draw", "çizmek", "VERBS"),
    KelimeEntity("paint", "boyamak", "VERBS"),
    KelimeEntity("sing", "şarkı söylemek", "VERBS"),
    KelimeEntity("dance", "dans etmek", "VERBS"),
    KelimeEntity("climb", "tırmanmak", "VERBS"),
    KelimeEntity("swim", "yüzmek", "VERBS"),
    KelimeEntity("jump", "zıplamak", "VERBS"),
    KelimeEntity("fall", "düşmek", "VERBS"),
    KelimeEntity("stand", "ayakta durmak", "VERBS"),
    KelimeEntity("sit", "oturmak", "VERBS"),
    KelimeEntity("lie", "uzanmak", "VERBS"),
    KelimeEntity("rest", "dinlenmek", "VERBS"),
    KelimeEntity("relax", "rahatlamak", "VERBS"),
    KelimeEntity("dream", "rüya görmek", "VERBS"),
    KelimeEntity("plan", "planlamak", "VERBS"),
    KelimeEntity("organize", "organize etmek", "VERBS"),
    KelimeEntity("control", "kontrol etmek", "VERBS"),
    KelimeEntity("manage", "yönetmek", "VERBS"),
    KelimeEntity("lead", "liderlik etmek", "VERBS"),
    KelimeEntity("follow", "takip etmek", "VERBS"),
    KelimeEntity("support", "desteklemek", "VERBS"),
    KelimeEntity("trust", "güvenmek", "VERBS"),
    KelimeEntity("doubt", "şüphe etmek", "VERBS"),
    KelimeEntity("risk", "risk almak", "VERBS"),
    KelimeEntity("win", "kazanmak", "VERBS"),
    KelimeEntity("fail", "başarısız olmak", "VERBS"),
        //VERBS 2.PAKET ZOR KISIM //

        KelimeEntity("accomplish", "başarmak", "VERBS"),
        KelimeEntity("acknowledge", "kabul etmek", "VERBS"),
        KelimeEntity("accumulate", "biriktirmek", "VERBS"),
        KelimeEntity("adapt", "uyum sağlamak", "VERBS"),
        KelimeEntity("administer", "yönetmek / uygulamak", "VERBS"),
        KelimeEntity("advocate", "savunmak", "VERBS"),
        KelimeEntity("allocate", "tahsis etmek", "VERBS"),
        KelimeEntity("anticipate", "beklemek / öngörmek", "VERBS"),
        KelimeEntity("appreciate", "takdir etmek", "VERBS"),
        KelimeEntity("articulate", "ifade etmek", "VERBS"),

        KelimeEntity("assess", "değerlendirmek", "VERBS"),
        KelimeEntity("attain", "elde etmek", "VERBS"),
        KelimeEntity("attribute", "atıfta bulunmak", "VERBS"),
        KelimeEntity("authorize", "yetkilendirmek", "VERBS"),
        KelimeEntity("avoid", "kaçınmak", "VERBS"),
        KelimeEntity("clarify", "netleştirmek", "VERBS"),
        KelimeEntity("collaborate", "iş birliği yapmak", "VERBS"),
        KelimeEntity("commence", "başlamak", "VERBS"),
        KelimeEntity("comply", "uymak", "VERBS"),
        KelimeEntity("comprehend", "kavramak", "VERBS"),

        KelimeEntity("conceive", "tasarlamak", "VERBS"),
        KelimeEntity("conclude", "sonuçlandırmak", "VERBS"),
        KelimeEntity("conduct", "yürütmek", "VERBS"),
        KelimeEntity("confine", "sınırlamak", "VERBS"),
        KelimeEntity("confront", "yüzleşmek", "VERBS"),
        KelimeEntity("consolidate", "pekiştirmek", "VERBS"),
        KelimeEntity("constrain", "kısıtlamak", "VERBS"),
        KelimeEntity("contemplate", "derin düşünmek", "VERBS"),
        KelimeEntity("contribute", "katkıda bulunmak", "VERBS"),
        KelimeEntity("convince", "ikna etmek", "VERBS"),

        KelimeEntity("coordinate", "koordine etmek", "VERBS"),
        KelimeEntity("cope", "başa çıkmak", "VERBS"),
        KelimeEntity("derive", "türetmek / elde etmek", "VERBS"),
        KelimeEntity("diminish", "azaltmak", "VERBS"),
        KelimeEntity("discern", "ayırt etmek", "VERBS"),
        KelimeEntity("disrupt", "aksatmak / bozmak", "VERBS"),
        KelimeEntity("elaborate", "detaylandırmak", "VERBS"),
        KelimeEntity("eliminate", "ortadan kaldırmak", "VERBS"),
        KelimeEntity("emphasize", "vurgulamak", "VERBS"),
        KelimeEntity("empower", "güçlendirmek", "VERBS"),

        KelimeEntity("encounter", "karşılaşmak", "VERBS"),
        KelimeEntity("enhance", "geliştirmek", "VERBS"),
        KelimeEntity("evaluate", "değerlendirmek", "VERBS"),
        KelimeEntity("facilitate", "kolaylaştırmak", "VERBS"),
        KelimeEntity("forecast", "tahmin etmek", "VERBS"),
        KelimeEntity("hinder", "engellemek", "VERBS"),
        KelimeEntity("implement", "uygulamak", "VERBS"),
        KelimeEntity("imply", "ima etmek", "VERBS"),
        KelimeEntity("integrate", "entegre etmek", "VERBS"),
        KelimeEntity("justify", "haklı çıkarmak", "VERBS"),

        KelimeEntity("maintain", "sürdürmek", "VERBS"),
        KelimeEntity("manipulate", "manipüle etmek", "VERBS"),
        KelimeEntity("negotiate", "müzakere etmek", "VERBS"),
        KelimeEntity("perceive", "algılamak", "VERBS"),
        KelimeEntity("preserve", "korumak", "VERBS"),
        KelimeEntity("prioritize", "önceliklendirmek", "VERBS"),
        KelimeEntity("proceed", "devam etmek", "VERBS"),
        KelimeEntity("regulate", "düzenlemek", "VERBS"),
        KelimeEntity("reinforce", "pekiştirmek", "VERBS"),
        KelimeEntity("resolve", "çözmek", "VERBS"),

        KelimeEntity("sustain", "devam ettirmek", "VERBS"),
        KelimeEntity("terminate", "sonlandırmak", "VERBS"),
        KelimeEntity("undermine", "zayıflatmak", "VERBS"),
        KelimeEntity("utilize", "kullanmak", "VERBS"),
        KelimeEntity("validate", "doğrulamak", "VERBS"),

        //SONRADAN GELEN İSİMLER AMA GENEL

        KelimeEntity("accurate", "doğru / hassas", "GENEL"),
        KelimeEntity("active", "aktif", "GENEL"),
        KelimeEntity("advanced", "ileri düzey", "GENEL"),
        KelimeEntity("affordable", "uygun fiyatlı", "GENEL"),
        KelimeEntity("aggressive", "agresif", "GENEL"),
        KelimeEntity("alert", "uyanık / dikkatli", "GENEL"),
        KelimeEntity("ambitious", "hırslı", "GENEL"),
        KelimeEntity("anxious", "endişeli", "GENEL"),
        KelimeEntity("appropriate", "uygun", "GENEL"),
        KelimeEntity("attractive", "çekici", "GENEL"),

        KelimeEntity("aware", "farkında", "GENEL"),
        KelimeEntity("balanced", "dengeli", "GENEL"),
        KelimeEntity("beneficial", "faydalı", "GENEL"),
        KelimeEntity("brilliant", "zeki / parlak", "GENEL"),
        KelimeEntity("capable", "yetenekli", "GENEL"),
        KelimeEntity("careless", "dikkatsiz", "GENEL"),
        KelimeEntity("challenging", "zorlayıcı", "GENEL"),
        KelimeEntity("complex", "karmaşık", "GENEL"),
        KelimeEntity("confident", "kendine güvenen", "GENEL"),
        KelimeEntity("conscious", "bilinçli", "GENEL"),

        KelimeEntity("consistent", "tutarlı", "GENEL"),
        KelimeEntity("convenient", "kullanışlı", "GENEL"),
        KelimeEntity("creative", "yaratıcı", "GENEL"),
        KelimeEntity("critical", "eleştirel / kritik", "GENEL"),
        KelimeEntity("curious", "meraklı", "GENEL"),
        KelimeEntity("dangerous", "tehlikeli", "GENEL"),
        KelimeEntity("decisive", "kararlı", "GENEL"),
        KelimeEntity("defensive", "savunmacı", "GENEL"),
        KelimeEntity("delicate", "narin / hassas", "GENEL"),
        KelimeEntity("demanding", "talepkâr", "GENEL"),

        KelimeEntity("dependent", "bağımlı", "GENEL"),
        KelimeEntity("determined", "azimli", "GENEL"),
        KelimeEntity("different", "farklı", "GENEL"),
        KelimeEntity("difficult", "zor", "GENEL"),
        KelimeEntity("efficient", "verimli", "GENEL"),
        KelimeEntity("emotional", "duygusal", "GENEL"),
        KelimeEntity("enthusiastic", "hevesli", "GENEL"),
        KelimeEntity("essential", "gerekli / temel", "GENEL"),
        KelimeEntity("eventual", "nihai", "GENEL"),
        KelimeEntity("expensive", "pahalı", "GENEL"),

        KelimeEntity("experienced", "deneyimli", "GENEL"),
        KelimeEntity("flexible", "esnek", "GENEL"),
        KelimeEntity("formal", "resmi", "GENEL"),
        KelimeEntity("frequent", "sık", "GENEL"),
        KelimeEntity("frustrated", "hayal kırıklığına uğramış", "GENEL"),
        KelimeEntity("generous", "cömert", "GENEL"),
        KelimeEntity("genuine", "gerçek / samimi", "GENEL"),
        KelimeEntity("gradual", "kademeli", "GENEL"),
        KelimeEntity("harmful", "zararlı", "GENEL"),
        KelimeEntity("helpful", "yardımcı", "GENEL"),

        KelimeEntity("hesitant", "kararsız", "GENEL"),
        KelimeEntity("honest", "dürüst", "GENEL"),
        KelimeEntity("ideal", "ideal", "GENEL"),
        KelimeEntity("independent", "bağımsız", "GENEL"),
        KelimeEntity("intelligent", "zeki", "GENEL"),
        KelimeEntity("intense", "yoğun", "GENEL"),
        KelimeEntity("interesting", "ilginç", "GENEL"),
        KelimeEntity("logical", "mantıklı", "GENEL"),
        KelimeEntity("loyal", "sadık", "GENEL"),
        KelimeEntity("massive", "devasa", "GENEL"),

        KelimeEntity("meaningful", "anlamlı", "GENEL"),
        KelimeEntity("mental", "zihinsel", "GENEL"),
        KelimeEntity("modern", "modern", "GENEL"),
        KelimeEntity("negative", "olumsuz", "GENEL"),
        KelimeEntity("obvious", "açık / belli", "GENEL"),
        KelimeEntity("ordinary", "sıradan", "GENEL"),
        KelimeEntity("organized", "düzenli", "GENEL"),
        KelimeEntity("patient", "sabırlı", "GENEL"),
        KelimeEntity("powerful", "güçlü", "GENEL"),
        KelimeEntity("practical", "pratik", "GENEL"),

        KelimeEntity("precise", "kesin", "GENEL"),
        KelimeEntity("predictable", "öngörülebilir", "GENEL"),
        KelimeEntity("productive", "üretken", "GENEL"),
        KelimeEntity("professional", "profesyonel", "GENEL"),
        KelimeEntity("realistic", "gerçekçi", "GENEL"),
        KelimeEntity("reliable", "güvenilir", "GENEL"),
        KelimeEntity("remarkable", "dikkat çekici", "GENEL"),
        KelimeEntity("responsible", "sorumlu", "GENEL"),
        KelimeEntity("sensitive", "hassas", "GENEL"),
        KelimeEntity("significant", "önemli", "GENEL"),

        KelimeEntity("similar", "benzer", "GENEL"),
        KelimeEntity("specific", "belirli", "GENEL"),
        KelimeEntity("stable", "istikrarlı", "GENEL"),
        KelimeEntity("strict", "katı", "GENEL"),
        KelimeEntity("successful", "başarılı", "GENEL"),
        KelimeEntity("suitable", "uygun", "GENEL"),
        KelimeEntity("supportive", "destekleyici", "GENEL"),
        KelimeEntity("suspicious", "şüpheli", "GENEL"),
        KelimeEntity("temporary", "geçici", "GENEL"),
        KelimeEntity("thoughtful", "düşünceli", "GENEL"),

        KelimeEntity("traditional", "geleneksel", "GENEL"),
        KelimeEntity("typical", "tipik", "GENEL"),
        KelimeEntity("uncertain", "belirsiz", "GENEL"),
        KelimeEntity("uncomfortable", "rahatsız", "GENEL"),
        KelimeEntity("unexpected", "beklenmedik", "GENEL"),
        KelimeEntity("unique", "benzersiz", "GENEL"),
        KelimeEntity("valuable", "değerli", "GENEL"),
        KelimeEntity("various", "çeşitli", "GENEL"),
        KelimeEntity("weak", "zayıf", "GENEL"),
        KelimeEntity("worthwhile", "değerli / yapmaya değer", "GENEL"),
        //ADJECTIVES
        KelimeEntity("accurate", "doğru / hassas", "ADJECTIVES"),
        KelimeEntity("active", "aktif", "ADJECTIVES"),
        KelimeEntity("advanced", "ileri düzey", "ADJECTIVES"),
        KelimeEntity("affordable", "uygun fiyatlı", "ADJECTIVES"),
        KelimeEntity("aggressive", "agresif", "ADJECTIVES"),
        KelimeEntity("alert", "uyanık / dikkatli", "ADJECTIVES"),
        KelimeEntity("ambitious", "hırslı", "ADJECTIVES"),
        KelimeEntity("anxious", "endişeli", "ADJECTIVES"),
        KelimeEntity("appropriate", "uygun", "ADJECTIVES"),
        KelimeEntity("attractive", "çekici", "ADJECTIVES"),

        KelimeEntity("aware", "farkında", "ADJECTIVES"),
        KelimeEntity("balanced", "dengeli", "ADJECTIVES"),
        KelimeEntity("beneficial", "faydalı", "ADJECTIVES"),
        KelimeEntity("brilliant", "zeki / parlak", "ADJECTIVES"),
        KelimeEntity("capable", "yetenekli", "ADJECTIVES"),
        KelimeEntity("careless", "dikkatsiz", "ADJECTIVES"),
        KelimeEntity("challenging", "zorlayıcı", "ADJECTIVES"),
        KelimeEntity("complex", "karmaşık", "ADJECTIVES"),
        KelimeEntity("confident", "kendine güvenen", "ADJECTIVES"),
        KelimeEntity("conscious", "bilinçli", "ADJECTIVES"),

        KelimeEntity("consistent", "tutarlı", "ADJECTIVES"),
        KelimeEntity("convenient", "kullanışlı", "ADJECTIVES"),
        KelimeEntity("creative", "yaratıcı", "ADJECTIVES"),
        KelimeEntity("critical", "eleştirel / kritik", "ADJECTIVES"),
        KelimeEntity("curious", "meraklı", "ADJECTIVES"),
        KelimeEntity("dangerous", "tehlikeli", "ADJECTIVES"),
        KelimeEntity("decisive", "kararlı", "ADJECTIVES"),
        KelimeEntity("defensive", "savunmacı", "ADJECTIVES"),
        KelimeEntity("delicate", "narin / hassas", "ADJECTIVES"),
        KelimeEntity("demanding", "talepkâr", "ADJECTIVES"),

        KelimeEntity("dependent", "bağımlı", "ADJECTIVES"),
        KelimeEntity("determined", "azimli", "ADJECTIVES"),
        KelimeEntity("different", "farklı", "ADJECTIVES"),
        KelimeEntity("difficult", "zor", "ADJECTIVES"),
        KelimeEntity("efficient", "verimli", "ADJECTIVES"),
        KelimeEntity("emotional", "duygusal", "ADJECTIVES"),
        KelimeEntity("enthusiastic", "hevesli", "ADJECTIVES"),
        KelimeEntity("essential", "gerekli / temel", "ADJECTIVES"),
        KelimeEntity("eventual", "nihai", "ADJECTIVES"),
        KelimeEntity("expensive", "pahalı", "ADJECTIVES"),

        KelimeEntity("experienced", "deneyimli", "ADJECTIVES"),
        KelimeEntity("flexible", "esnek", "ADJECTIVES"),
        KelimeEntity("formal", "resmi", "ADJECTIVES"),
        KelimeEntity("frequent", "sık", "ADJECTIVES"),
        KelimeEntity("frustrated", "hayal kırıklığına uğramış", "ADJECTIVES"),
        KelimeEntity("generous", "cömert", "ADJECTIVES"),
        KelimeEntity("genuine", "gerçek / samimi", "ADJECTIVES"),
        KelimeEntity("gradual", "kademeli", "ADJECTIVES"),
        KelimeEntity("harmful", "zararlı", "ADJECTIVES"),
        KelimeEntity("helpful", "yardımcı", "ADJECTIVES"),

        KelimeEntity("hesitant", "kararsız", "ADJECTIVES"),
        KelimeEntity("honest", "dürüst", "ADJECTIVES"),
        KelimeEntity("ideal", "ideal", "ADJECTIVES"),
        KelimeEntity("independent", "bağımsız", "ADJECTIVES"),
        KelimeEntity("intelligent", "zeki", "ADJECTIVES"),
        KelimeEntity("intense", "yoğun", "ADJECTIVES"),
        KelimeEntity("interesting", "ilginç", "ADJECTIVES"),
        KelimeEntity("logical", "mantıklı", "ADJECTIVES"),
        KelimeEntity("loyal", "sadık", "ADJECTIVES"),
        KelimeEntity("massive", "devasa", "ADJECTIVES"),

        KelimeEntity("meaningful", "anlamlı", "ADJECTIVES"),
        KelimeEntity("mental", "zihinsel", "ADJECTIVES"),
        KelimeEntity("modern", "modern", "ADJECTIVES"),
        KelimeEntity("negative", "olumsuz", "ADJECTIVES"),
        KelimeEntity("obvious", "açık / belli", "ADJECTIVES"),
        KelimeEntity("ordinary", "sıradan", "ADJECTIVES"),
        KelimeEntity("organized", "düzenli", "ADJECTIVES"),
        KelimeEntity("patient", "sabırlı", "ADJECTIVES"),
        KelimeEntity("powerful", "güçlü", "ADJECTIVES"),
        KelimeEntity("practical", "pratik", "ADJECTIVES"),

        KelimeEntity("precise", "kesin", "ADJECTIVES"),
        KelimeEntity("predictable", "öngörülebilir", "ADJECTIVES"),
        KelimeEntity("productive", "üretken", "ADJECTIVES"),
        KelimeEntity("professional", "profesyonel", "ADJECTIVES"),
        KelimeEntity("realistic", "gerçekçi", "ADJECTIVES"),
        KelimeEntity("reliable", "güvenilir", "ADJECTIVES"),
        KelimeEntity("remarkable", "dikkat çekici", "ADJECTIVES"),
        KelimeEntity("responsible", "sorumlu", "ADJECTIVES"),
        KelimeEntity("sensitive", "hassas", "ADJECTIVES"),
        KelimeEntity("significant", "önemli", "ADJECTIVES"),

        KelimeEntity("similar", "benzer", "ADJECTIVES"),
        KelimeEntity("specific", "belirli", "ADJECTIVES"),
        KelimeEntity("stable", "istikrarlı", "ADJECTIVES"),
        KelimeEntity("strict", "katı", "ADJECTIVES"),
        KelimeEntity("successful", "başarılı", "ADJECTIVES"),
        KelimeEntity("suitable", "uygun", "ADJECTIVES"),
        KelimeEntity("supportive", "destekleyici", "ADJECTIVES"),
        KelimeEntity("suspicious", "şüpheli", "ADJECTIVES"),
        KelimeEntity("temporary", "geçici", "ADJECTIVES"),
        KelimeEntity("thoughtful", "düşünceli", "ADJECTIVES"),

        KelimeEntity("traditional", "geleneksel", "ADJECTIVES"),
        KelimeEntity("typical", "tipik", "ADJECTIVES"),
        KelimeEntity("uncertain", "belirsiz", "ADJECTIVES"),
        KelimeEntity("uncomfortable", "rahatsız", "ADJECTIVES"),
        KelimeEntity("unexpected", "beklenmedik", "ADJECTIVES"),
        KelimeEntity("unique", "benzersiz", "ADJECTIVES"),
        KelimeEntity("valuable", "değerli", "ADJECTIVES"),
        KelimeEntity("various", "çeşitli", "ADJECTIVES"),
        KelimeEntity("weak", "zayıf", "ADJECTIVES"),
        KelimeEntity("worthwhile", "değerli / yapmaya değer", "ADJECTIVES"),
        // ADJECTIVES 2. PAKET ***--------//
        KelimeEntity("abstract", "soyut", "ADJECTIVES"),
        KelimeEntity("accurate", "kesin / doğru", "ADJECTIVES"),
        KelimeEntity("adequate", "yeterli", "ADJECTIVES"),
        KelimeEntity("ambiguous", "belirsiz", "ADJECTIVES"),
        KelimeEntity("anonymous", "anonim", "ADJECTIVES"),
        KelimeEntity("artificial", "yapay", "ADJECTIVES"),
        KelimeEntity("awkward", "garip / rahatsız edici", "ADJECTIVES"),
        KelimeEntity("biased", "taraflı", "ADJECTIVES"),
        KelimeEntity("brief", "kısa", "ADJECTIVES"),
        KelimeEntity("broad", "geniş", "ADJECTIVES"),

        KelimeEntity("cautious", "temkinli", "ADJECTIVES"),
        KelimeEntity("coherent", "tutarlı", "ADJECTIVES"),
        KelimeEntity("complicated", "karmaşık", "ADJECTIVES"),
        KelimeEntity("controversial", "tartışmalı", "ADJECTIVES"),
        KelimeEntity("crucial", "hayati", "ADJECTIVES"),
        KelimeEntity("dense", "yoğun", "ADJECTIVES"),
        KelimeEntity("distinct", "farklı / belirgin", "ADJECTIVES"),
        KelimeEntity("dramatic", "dramatik", "ADJECTIVES"),
        KelimeEntity("efficient", "etkili / verimli", "ADJECTIVES"),
        KelimeEntity("evident", "açıkça görülen", "ADJECTIVES"),

        KelimeEntity("excessive", "aşırı", "ADJECTIVES"),
        KelimeEntity("explicit", "açık / net", "ADJECTIVES"),
        KelimeEntity("external", "harici", "ADJECTIVES"),
        KelimeEntity("faint", "silik / baygın", "ADJECTIVES"),
        KelimeEntity("feasible", "yapılabilir", "ADJECTIVES"),
        KelimeEntity("firm", "sağlam / kesin", "ADJECTIVES"),
        KelimeEntity("fragile", "kırılgan", "ADJECTIVES"),
        KelimeEntity("hostile", "düşmanca", "ADJECTIVES"),
        KelimeEntity("immediate", "hemen / acil", "ADJECTIVES"),
        KelimeEntity("inevitable", "kaçınılmaz", "ADJECTIVES"),

        KelimeEntity("informal", "resmi olmayan", "ADJECTIVES"),
        KelimeEntity("inner", "iç", "ADJECTIVES"),
        KelimeEntity("intellectual", "entelektüel", "ADJECTIVES"),
        KelimeEntity("irrelevant", "alakasız", "ADJECTIVES"),
        KelimeEntity("isolated", "izole", "ADJECTIVES"),
        KelimeEntity("lengthy", "uzun", "ADJECTIVES"),
        KelimeEntity("minor", "önemsiz", "ADJECTIVES"),
        KelimeEntity("mutual", "karşılıklı", "ADJECTIVES"),
        KelimeEntity("neutral", "tarafsız", "ADJECTIVES"),
        KelimeEntity("notable", "kayda değer", "ADJECTIVES"),

        KelimeEntity("objective", "nesnel", "ADJECTIVES"),
        KelimeEntity("optional", "isteğe bağlı", "ADJECTIVES"),
        KelimeEntity("partial", "kısmi", "ADJECTIVES"),
        KelimeEntity("persistent", "ısrarcı", "ADJECTIVES"),
        KelimeEntity("potential", "potansiyel", "ADJECTIVES"),
        KelimeEntity("precautionary", "önleyici", "ADJECTIVES"),
        KelimeEntity("prominent", "öne çıkan", "ADJECTIVES"),
        KelimeEntity("random", "rastgele", "ADJECTIVES"),
        KelimeEntity("rare", "nadir", "ADJECTIVES"),
        KelimeEntity("rough", "pürüzlü / kaba", "ADJECTIVES"),

        KelimeEntity("subtle", "ince / belirsiz", "ADJECTIVES"),
        KelimeEntity("sufficient", "yeterli", "ADJECTIVES"),
        KelimeEntity("tense", "gergin", "ADJECTIVES"),
        KelimeEntity("tricky", "hileli / zor", "ADJECTIVES"),
        KelimeEntity("ultimate", "nihai", "ADJECTIVES"),
        KelimeEntity("unclear", "belirsiz", "ADJECTIVES"),
        KelimeEntity("universal", "evrensel", "ADJECTIVES"),
        KelimeEntity("vague", "muğlak", "ADJECTIVES"),
        KelimeEntity("vital", "hayati", "ADJECTIVES"),
        KelimeEntity("widespread", "yaygın", "ADJECTIVES"),





        )
}


