package com.example.englishwords2

object KelimeSeedData {

    fun getKelimeler(): List<KelimeEntity> = listOf(
        KelimeEntity(ingilizce = "pencil", turkce = "kalem"),
        KelimeEntity(ingilizce = "car", turkce = "araba"),
        KelimeEntity(ingilizce = "book", turkce = "kitap"),
        KelimeEntity(ingilizce = "table", turkce = "masa"),
        KelimeEntity(ingilizce = "chair", turkce = "sandalye"),
        KelimeEntity(ingilizce = "phone", turkce = "telefon"),
        KelimeEntity(ingilizce = "house", turkce = "ev"),
        KelimeEntity(ingilizce = "door", turkce = "kapı"),
        KelimeEntity(ingilizce = "window", turkce = "pencere"),
        KelimeEntity(ingilizce = "water", turkce = "su"),
        KelimeEntity(ingilizce = "food", turkce = "yemek"),
        KelimeEntity(ingilizce = "school", turkce = "okul"),
        KelimeEntity(ingilizce = "bag", turkce = "çanta"),
        KelimeEntity(ingilizce = "road", turkce = "yol"),
        KelimeEntity(ingilizce = "tree", turkce = "ağaç"),
        KelimeEntity(ingilizce = "sun", turkce = "güneş"),
        KelimeEntity(ingilizce = "moon", turkce = "ay"),
        KelimeEntity(ingilizce = "pen", turkce = "tükenmez kalem"),
        KelimeEntity(ingilizce = "clock", turkce = "saat"),
        KelimeEntity(ingilizce = "bread", turkce = "ekmek"),
        KelimeEntity("accountant", "muhasebeci"),
    KelimeEntity("afraid", "korkmuş"),
    KelimeEntity("age", "yaş"),
    KelimeEntity("airplane", "uçak"),
    KelimeEntity("alone", "yalnız"),
    KelimeEntity("angry", "kızgın-sinirli"),
    KelimeEntity("animal", "hayvan"),
    KelimeEntity("answer", "cevap vermek"),
    KelimeEntity("architect", "mimar"),
    KelimeEntity("arrive", "varmak"),
    KelimeEntity("aunt", "hala-teyze"),
    KelimeEntity("bag", "çanta"),
    KelimeEntity("ball", "top"),
    KelimeEntity("bath", "banyo"),
    KelimeEntity("beautiful", "güzel"),
    KelimeEntity("bill", "hesap-fatura"),
    KelimeEntity("body", "vücut"),
    KelimeEntity("boil", "kaynamak"),
    KelimeEntity("bookstore", "kitapçı"),
    KelimeEntity("boring", "sıkıcı"),
    KelimeEntity("borrow", "ödünç almak"),
    KelimeEntity("boss", "patron"),
    KelimeEntity("bottle", "şişe"),
    KelimeEntity("box", "kutu"),
    KelimeEntity("brave", "cesur"),
    KelimeEntity("bread", "ekmek"),
    KelimeEntity("break", "kırmak"),
    KelimeEntity("bridge", "köprü"),
    KelimeEntity("brush", "fırça"),
    KelimeEntity("build", "inşa etmek"),
    KelimeEntity("butter", "tere yağı"),
    KelimeEntity("calculator", "hesap makinası"),
    KelimeEntity("calendar", "takvim"),
    KelimeEntity("call", "aramak"),
    KelimeEntity("capital", "başkent"),
    KelimeEntity("carpenter", "marangoz"),
    KelimeEntity("carpet", "halı"),
    KelimeEntity("carry", "taşımak"),
    KelimeEntity("cartoon", "çizgi film"),
    KelimeEntity("chair", "sandalye"),
    KelimeEntity("cheap", "ucuz"),
    KelimeEntity("cheese", "peynir"),
    KelimeEntity("cherry", "kiraz"),
    KelimeEntity("chicken", "tavuk"),
    KelimeEntity("church", "kilise"),
    KelimeEntity("clean", "temizlemek"),
    KelimeEntity("clear", "açık, net"),
    KelimeEntity("clever", "akıllı"),
    KelimeEntity("clock", "saat"),
    KelimeEntity("cloud", "bulut"),

    // ===== PAKET 2 =====
    KelimeEntity("plane", "uçak"),
    KelimeEntity("pocket", "cep"),
    KelimeEntity("polite", "kibar"),
    KelimeEntity("pool", "havuz"),
    KelimeEntity("poor", "fakir"),
    KelimeEntity("possible", "mümkün"),
    KelimeEntity("push", "ittirmek"),
    KelimeEntity("quick", "hızlı"),
    KelimeEntity("quiet", "sessiz"),
    KelimeEntity("railway", "tren yolu"),
    KelimeEntity("ready", "hazır"),
    KelimeEntity("refrigerator", "buzdolabı"),
    KelimeEntity("remember", "hatırlamak"),
    KelimeEntity("rent", "kiralamak"),
    KelimeEntity("repair", "tamir etmek"),
    KelimeEntity("repeat", "tekrar etmek"),
    KelimeEntity("restroom", "tuvalet"),
    KelimeEntity("return", "geri dönmek"),
    KelimeEntity("rice", "pirinç"),
    KelimeEntity("rich", "zengin"),
    KelimeEntity("ride", "binmek"),
    KelimeEntity("right", "doğru"),
    KelimeEntity("ring", "yüzük-telefonun çalması"),
    KelimeEntity("rise", "güneş(doğmak)"),
    KelimeEntity("river", "ırmak"),
    KelimeEntity("road", "yol"),
    KelimeEntity("roof", "çatı"),
    KelimeEntity("room", "oda"),
    KelimeEntity("rose", "gül"),
    KelimeEntity("salt", "tuz"),
    KelimeEntity("same", "aynı"),
    KelimeEntity("security", "güvenlik"),
    KelimeEntity("sell", "satmak"),
    KelimeEntity("serious", "ciddi"),
    KelimeEntity("shelf", "raf"),
    KelimeEntity("ship", "gemi"),
    KelimeEntity("shirt", "gömlek"),
    KelimeEntity("shoe", "ayakkabı"),
    KelimeEntity("show", "göstermek"),
    KelimeEntity("sick", "hasta"),
    KelimeEntity("sing", "şarkı söylemek"),
    KelimeEntity("single", "bekar"),
    KelimeEntity("skirt", "etek"),
    KelimeEntity("sky", "gökyüzü"),
    KelimeEntity("smile", "gülümsemek"),
    KelimeEntity("snow", "kar"),
    KelimeEntity("socks", "çorap"),
    KelimeEntity("son", "erkek kardeş"),
    KelimeEntity("song", "şarkı"),
    KelimeEntity("soup", "çorba"),

    // ===== PAKET 3 =====
    KelimeEntity("serve", "servis yapmak"),
    KelimeEntity("sharp", "keskin,sivri"),
    KelimeEntity("shine", "parlamak"),
    KelimeEntity("shoulder", "omuz"),
    KelimeEntity("shout", "bağırmak"),
    KelimeEntity("sign", "imza atmak"),
    KelimeEntity("silent", "sessiz"),
    KelimeEntity("simple", "basit"),
    KelimeEntity("situation", "durum"),
    KelimeEntity("ski", "kayak"),
    KelimeEntity("snake", "yılan"),
    KelimeEntity("soap", "sabun"),
    KelimeEntity("society", "sosyete"),
    KelimeEntity("soft", "yumuşak"),
    KelimeEntity("spider", "örümcek"),
    KelimeEntity("stand", "ayakta durmak"),
    KelimeEntity("stone", "taş"),
    KelimeEntity("storm", "fırtına"),
    KelimeEntity("subway", "metro"),
    KelimeEntity("sure", "emin olmak"),
    KelimeEntity("surprised", "şaşırmış"),
    KelimeEntity("tailor", "terzi"),
    KelimeEntity("taste", "tatmak"),
    KelimeEntity("team", "takım"),
    KelimeEntity("temperature", "derece,ısı"),
    KelimeEntity("tent", "çadır"),
    KelimeEntity("terrible", "berbat"),
    KelimeEntity("throw", "atmak,fırlatmak"),
    KelimeEntity("tiger", "kaplan"),
    KelimeEntity("tissue", "kağıt mendil"),
    KelimeEntity("tongue", "dil"),
    KelimeEntity("touch", "dokumak"),
    KelimeEntity("transport", "nakil, taşıma"),
    KelimeEntity("trouble", "dert"),
    KelimeEntity("try", "denemek"),
    KelimeEntity("usual", "olağan"),
    KelimeEntity("vacation", "tatil"),
    KelimeEntity("vacuum cleaner", "elektrik süpürgesi"),
    KelimeEntity("valuable", "değerli"),
    KelimeEntity("vegetable", "sebze"),
    KelimeEntity("view", "manzara, görünüm"),
    KelimeEntity("voice", "ses"),
    KelimeEntity("war", "savaş"),
    KelimeEntity("warm", "ılık"),
    KelimeEntity("warning", "uyarı"),
    KelimeEntity("weather", "hava"),
    KelimeEntity("wet", "ıslak"),
    KelimeEntity("win", "kazanmak"),
    KelimeEntity("wine", "şarap"),
    KelimeEntity("worry", "endişe"),

    // ===== PAKET 4 =====
    KelimeEntity("coin", "madeni para"),
    KelimeEntity("comb", "tarak"),
    KelimeEntity("common", "yaygın"),
    KelimeEntity("communicate", "iletişim kurmak"),
    KelimeEntity("compare", "kıyaslamak"),
    KelimeEntity("complain", "şikayet etmek"),
    KelimeEntity("connected flight", "aktarmalı uçuş"),
    KelimeEntity("consist", "oluşmak"),
    KelimeEntity("contain", "içermek"),
    KelimeEntity("convince", "ikna etmek"),
    KelimeEntity("count", "saymak"),
    KelimeEntity("crime", "suç"),
    KelimeEntity("criticize", "eleştiri yapmak"),
    KelimeEntity("curtain", "perde"),
    KelimeEntity("death", "ölüm"),
    KelimeEntity("decrease", "azalmak"),
    KelimeEntity("defend", "savunmak"),
    KelimeEntity("departure gate", "çıkış kapısı"),
    KelimeEntity("destination", "varış"),
    KelimeEntity("destroy", "yok etmek"),
    KelimeEntity("detail", "detay"),
    KelimeEntity("development", "gelişim"),
    KelimeEntity("disagree", "aynı fikirde olmamak"),
    KelimeEntity("discount", "indirim"),
    KelimeEntity("disease", "hastalık"),
    KelimeEntity("dive", "dalmak"),
    KelimeEntity("divide", "bölmek"),
    KelimeEntity("domestic flight", "iç hat uçuşu"),
    KelimeEntity("drop", "düşürmek"),
    KelimeEntity("drug", "ilaç,uyuşturucu"),
    KelimeEntity("dry", "kuru"),
    KelimeEntity("duty", "görev"),
    KelimeEntity("earthquake", "deprem"),
    KelimeEntity("education", "eğitim"),
    KelimeEntity("effort", "çaba"),
    KelimeEntity("elegant", "zarif"),
    KelimeEntity("employer", "işveren"),
    KelimeEntity("engine", "motor"),
    KelimeEntity("environment", "çevre"),
    KelimeEntity("event", "etkinlik,olay"),
    KelimeEntity("excuse", "mazeret"),
    KelimeEntity("expect", "ummak"),
    KelimeEntity("explosion", "patlama"),
    KelimeEntity("express", "ifade etmek"),
    KelimeEntity("fact", "gerçek"),
    KelimeEntity("fair", "adil"),
    KelimeEntity("fear", "korkmak"),
    KelimeEntity("feed", "beslemek"),
    KelimeEntity("field", "tarla"),
    KelimeEntity("fist", "yumruk"),

    // ===== PAKET 5 =====
    KelimeEntity("client", "müşteri"),
    KelimeEntity("coal", "kömür"),
    KelimeEntity("comment", "yorum"),
    KelimeEntity("commerce", "ticaret"),
    KelimeEntity("commercial", "reklam"),
    KelimeEntity("community", "cemiyet"),
    KelimeEntity("competition", "rekabet"),
    KelimeEntity("complaint", "şikayet"),
    KelimeEntity("concentrate", "konsantre olmak"),
    KelimeEntity("condition", "durum,koşul"),
    KelimeEntity("confess", "itirafta bulunmak"),
    KelimeEntity("congratulate", "tebrik etmek"),
    KelimeEntity("congress", "kongre,meclis"),
    KelimeEntity("consider", "göz önünde bulundurmak"),
    KelimeEntity("construction", "inşaat"),
    KelimeEntity("consult", "danışmak"),
    KelimeEntity("contest", "yarışma"),
    KelimeEntity("contribute", "katkıda bulunmak"),
    KelimeEntity("convert", "dönüştürmek"),
    KelimeEntity("court", "mahkeme"),
    KelimeEntity("crossword", "bulmaca"),
    KelimeEntity("cruel", "zalim"),
    KelimeEntity("customs", "gümrük,töre"),
    KelimeEntity("dashboard", "gösterge paneli"),
    KelimeEntity("deadline", "son tarih"),
    KelimeEntity("deceive", "aldatmak"),
    KelimeEntity("declare", "ilan etmek"),
    KelimeEntity("define", "tanımlamak"),
    KelimeEntity("deflation", "deflasyon,çökme"),
    KelimeEntity("depend", "dayanmak / bağlı olmak"),
    KelimeEntity("desire", "arzu etmek"),
    KelimeEntity("devaluation", "değer düşürme"),
    KelimeEntity("diagnose", "teşhis"),
    KelimeEntity("disappear", "ortadan kaybolmak"),
    KelimeEntity("disappoint", "hayal kırıklığına uğramak"),
    KelimeEntity("distance", "mesafe"),
    KelimeEntity("distribution", "dağıtım"),
    KelimeEntity("dreadful", "korkunç"),
    KelimeEntity("eager", "hevesli"),
    KelimeEntity("election", "seçim"),
    KelimeEntity("embassy", "büyükelçilik"),
    KelimeEntity("encourage", "teşvik etmek"),
    KelimeEntity("enemy", "düşman"),
    KelimeEntity("enterprise", "işletme,şirket"),
    KelimeEntity("entrepreneur", "girişimci,işletmeci"),
    KelimeEntity("envy", "imrenmek"),
    KelimeEntity("essay", "makale"),
    KelimeEntity("establish", "kurmak"),
    KelimeEntity("estimate", "tahmin etmek"),
    KelimeEntity("evaluate", "değerlendirmek")
    )
}


